export const defaultTheme = {
  colors: {
    lightGrey: '#F8F8F8',
    darkGrey: '#7E7E7E',
    defaultBalck: '#000000',
    defaulWhite: '#FFFFFF',
  },
  fontFamily: 'Nunito',
  fontSizeDefault: '16px',
  lineHeightDefault: '26px',
  fontWeightDefault: '400',
  mobileWidth: '360px',
  tabletWidth: '768px',
  laptopWidth: '1024px',
  desctopWidth: '1170px',
  mobilePadding: '16px',
  tabletPadding: '32px',
  laptopPadding: '60px',
  headerHeight: '200px',
};
